apiVersion: apps/v1
kind: Deployment
metadata:
  name: emotion-detection-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: emotion-detection-container
        image: kashifsadiq/emotion9:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
